# Generated by Django 4.2.9 on 2025-12-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(help_text='IP của C# Server', max_length=50)),
                ('filename', models.CharField(help_text='Tên file video', max_length=255)),
                ('file_path', models.FileField(help_text='Đường dẫn file trong media/', upload_to='screen_recordings/%Y/%m/%d/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian ghi')),
                ('file_size', models.IntegerField(help_text='Kích thước file (bytes)')),
                ('duration', models.IntegerField(default=0, help_text='Độ dài video (giây)')),
            ],
            options={
                'verbose_name': 'Screen Recording',
                'verbose_name_plural': 'Screen Recordings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
